from datetime import datetime

from sqlalchemy import JSON, ForeignKey, Integer, String, Boolean, DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String)
    email: Mapped[str] = mapped_column(String, unique=True)
    hashed_password: Mapped[str] = mapped_column(String, nullable=False, default="")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    candidate_profile: Mapped["CandidateProfile"] = relationship(
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",   
    )


class CandidateProfile(Base):
    __tablename__ = "candidate_profiles"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    resume_id: Mapped[int] = mapped_column(Integer, ForeignKey("resumes.id"), nullable=True)  
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False, unique=True)  

    # Spec R1-R5: filter inputs used by Job Search Agent
    role_preference: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    preferred_location: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    experience_years_min: Mapped[int] = mapped_column(Integer, nullable=False)
    experience_years_max: Mapped[int] = mapped_column(Integer, nullable=False)
    salary_min: Mapped[int] = mapped_column(Integer, nullable=False)
    salary_max: Mapped[int] = mapped_column(Integer, nullable=False)
    remote_opt_in: Mapped[bool] = mapped_column(Boolean, default=False)  # R5

    # Scoring Algorithm spec S1: normalized skills, extracted ONCE from resume
    # at upload time via LLM. Null until first successful extraction.
    skills: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)

    resume: Mapped["Resume"] = relationship(back_populates="candidate_profile")
    user: Mapped["User"] = relationship(
        back_populates="candidate_profile"
    )


class Resume(Base):
    __tablename__ = "resumes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    resume_file_path: Mapped[str] = mapped_column(String)

    candidate_profile: Mapped["CandidateProfile"] = relationship(back_populates="resume")


# ---------------------------------------------------------------------------
# Job Search Agent — matches Spec Section 4 (Data Written to Database)
# and Architecture doc Section 4 (job_id strategy)
# ---------------------------------------------------------------------------
class JobPosting(Base):
    __tablename__ = "jobs"

    # job_id: hash-based, generated by Job Search Agent at fetch time.
    # Serves as both primary key AND dedup check (Architecture doc, Section 4).
    job_id: Mapped[str] = mapped_column(String, primary_key=True)

    title: Mapped[str] = mapped_column(String, nullable=False)          # spec: title
    company_name: Mapped[str] = mapped_column(String, nullable=False)   # spec: company
    location: Mapped[str] = mapped_column(String, nullable=False)       # spec: location

    # R8: salary may be missing -> nullable. Normalized to yearly (R7) before storing.
    salary_min: Mapped[int | None] = mapped_column(Integer, nullable=True)
    salary_max: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # R9: experience may be missing -> nullable.
    experience_required_years: Mapped[int | None] = mapped_column(Integer, nullable=True)

    apply_link: Mapped[str | None] = mapped_column(String, nullable=True)  # R9a: source may hide it
    platform: Mapped[str] = mapped_column(String, nullable=False)       # platform source (e.g. "indeed")
    is_remote: Mapped[bool] = mapped_column(Boolean, default=False)     # supports R5 remote opt-in matching

    fetched_at: Mapped[datetime] = mapped_column(               # spec: fetched timestamp
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Stored so Scoring Algorithm (and any future re-scoring, e.g. after a
    # resume update) has the source text without re-fetching from Apify.
    # Populated by Job Search Agent at fetch time; read (not written) by Scoring Algorithm.
    description: Mapped[str | None] = mapped_column(String, nullable=True)

    # Scoring Algorithm spec S2: normalized required skills, extracted from
    # `description` via LLM. Written by Scoring Algorithm AFTER this row
    # already exists (Job Search Agent does not populate this column).
    # Null if extraction found nothing (S5 -> score defaults to 0 in that case).
    required_skills: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)


# ---------------------------------------------------------------------------
# Scoring Algorithm — matches Scoring Algorithm Spec Section 4
# ---------------------------------------------------------------------------
class Score(Base):
    __tablename__ = "scores"

    job_id: Mapped[str] = mapped_column(String, ForeignKey("jobs.job_id"), primary_key=True)

    score: Mapped[int] = mapped_column(Integer, nullable=False)  # S4: (matched/required)*100, 0-100

    # S5: assumption confirmed via schema design discussion — stored so
    # Content Generator can reference specifics later (e.g. "4 of 5 skills match")
    matched_skills: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    missing_skills: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)

    scored_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )